### ISSUE TITLE
ERROR - Unable to serialize to JSON. Bad data found

### ISSUE THREAD

**Issue by jazzyisj** [dcshoecomp/noaa_alerts#10]
```
2021-02-03 23:22:25 ERROR (SyncWorker_33) [custom_components.noaa_alerts.sensor] Maximum retries exceeded. Response object dump: <Response [503]>
2021-02-03 23:22:26 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(event: state_changed).data.new_state(state: sensor.noaa_alerts_miz076).attributes.description=Maximum retries exceeded. Response object dump: <Response [503]>(<class 'Exception'>
```

Getting a lot of these in the log.  Not sure when it started appearing.  Sensor appears to be functioning though.
![image](https://user-images.githubusercontent.com/44064559/106844918-c825e480-6677-11eb-963a-98c4229ead93.png)

**Comment by dcshoecomp** [comment]
Did these errors clear themselves up? 503 is a service unavailable. Maybe noaa was having connection issues.

**Comment by dcshoecomp** [comment]
> Did these errors clear themselves up? 503 is a service unavailable. Maybe noaa was having connection issues.



> ```
> 2021-02-03 23:22:25 ERROR (SyncWorker_33) [custom_components.noaa_alerts.sensor] Maximum retries exceeded. Response object dump: <Response [503]>
> 2021-02-03 23:22:26 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(event: state_changed).data.new_state(state: sensor.noaa_alerts_miz076).attributes.description=Maximum retries exceeded. Response object dump: <Response [503]>(<class 'Exception'>
> ```
> 
> Getting a lot of these in the log. Not sure when it started appearing. Sensor appears to be functioning though.
> ![image](https://user-images.githubusercontent.com/44064559/106844918-c825e480-6677-11eb-963a-98c4229ead93.png)

Did these errors clear themselves up? 503 is a service unavailable. Maybe noaa was having connection issues.

**Comment by jazzyisj** [comment]
No.  And when those errors start happening (always when there is an active alert it seems) it hangs up lovelace.  I had to disable the sensor and reboot to get my UI back.

I hope you find a fix.  I really like this integration!  Let me know if there's any more data or logs I can grab if it helps.

**Comment by dcshoecomp** [comment]
Hmm I wonder if it has to do with specifically that location. I'll spin a a
test container to see if I can replicate it.
Mine has been running and giving me alerts without issue.

**Comment by dcshoecomp** [comment]
I updated the default scan interval and it seemed to clear up the issue. Noaa is probably limiting the number of public API requests.

**Comment by jazzyisj** [comment]
Just an update on this.  It still happens occasionally, today being one of those days.

```
ERROR (SyncWorker_14) [custom_components.noaa_alerts.sensor] Maximum retries exceeded. Response object dump: <Response [200]>
ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: sensor.noaa_alerts_miz076).attributes.description=Maximum retries exceeded. Response object dump: <Response [200]>(<class 'Exception'>
```
However, I also recently installed NWS weather integration.  At the same time I was getting the errors from your component I was also getting this.

`ERROR (MainThread) [homeassistant.components.nws] Error requesting NWS forecast hourly station KDTW data: 502, message='Bad Gateway', url=URL('https://api.weather.gov/gridpoints/DTX/68,35/forecast/hourly')`

So I think it's save to assume NOAA (at least for my area) is down when this is happening.

**Comment by jazzyisj** [comment]
I never was able to narrow down exactly what was causing this but it rarely happens now and I'm pretty sure it's on the NOAA/NWS end, not yours.  Closing.
