### ISSUE TITLE
HASS v2021.12  implements device_state_attributes warning

### ISSUE THREAD

**Issue by jazzyisj** [dcshoecomp/noaa_alerts#11]
`WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.noaa_alerts_miz076 (<class 'custom_components.noaa_alerts.sensor.noaa_alertsSensor'>) implements device_state_attributes. Please report it to the custom component author.`

Just a heads up - I'm running the 2021.12 beta and this integration (along with many others) throwing this warning.

**Comment by dcshoecomp** [comment]
> `WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.noaa_alerts_miz076 (<class 'custom_components.noaa_alerts.sensor.noaa_alertsSensor'>) implements device_state_attributes. Please report it to the custom component author.`
> 
> Just a heads up - I'm running the 2021.12 beta and this integration (along with many others) throwing this warning.

Thanks for the heads up. I will look into what the new way I should be doing attributes and make the changes.
