### ISSUE TITLE
Integration not found error

### ISSUE THREAD

**Issue by atomicpapa** [dcshoecomp/noaa_alerts#7]
HA Version 0.96.5
HA running in Docker on Ubuntu 18.04 LTS
Not Hassio

Trying to get this up and running.and getting an "Integration noaa_alerts not found" error when I check config.  I cloned the git repository and moved the files into the correct location - custom_components/noaa_alerts.

Added to config under `sensor:` as follows:
```
  - platform: noaa_alerts
    zoneid: TXZ205
```

**Comment by DeadEnded** [comment]
Can you please confirm where the sensor.py is location?
Is it in custom_components/noaa_alerts/sensor.py
OR
custom_components/noaa_alerts/custom_components/sensor.py

If it is the latter, your files are in the wrong location - move everything in the sub custom_components folder to the noaa_alerts folder.

**Comment by atomicpapa** [comment]
solved my installing with HACS
